name: Build Site
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Install deps
        run: |
          npm install postcss-cli
          npm install autoprefixer
      - name: Build pages
        run: make build